# Generated by Django 2.1.5 on 2019-01-13 14:15

import datetime
import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, max_length=30)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('body', models.TextField()),
            ],
        ),
    ]
