# Generated by Django 2.1.5 on 2019-01-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20190113_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='author',
            field=models.CharField(default='<bound method AbstractBaseUser.get_username of <User: sourav>>', max_length=50),
        ),
    ]
