# Generated by Django 2.1.5 on 2019-01-28 19:27

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20190125_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tweets',
            name='author',
            field=models.CharField(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, max_length=50),
        ),
    ]
