# Generated by Django 2.1.5 on 2019-02-03 09:23

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_auto_20190203_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='author',
            field=models.CharField(max_length=50, verbose_name=django.contrib.auth.base_user.AbstractBaseUser.get_username),
        ),
    ]
