# Generated by Django 2.1.5 on 2019-02-03 12:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0018_auto_20190203_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='author',
            field=models.CharField(default="<class 'django.contrib.auth.models.User'>", max_length=30, verbose_name=django.contrib.auth.models.User),
        ),
    ]
