# Generated by Django 2.1.5 on 2019-02-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0022_auto_20190203_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='author',
            field=models.CharField(max_length=30, verbose_name='auth.User'),
        ),
    ]
