# Generated by Django 2.1.5 on 2019-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0025_auto_20190203_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='author',
            field=models.CharField(default='auth.User', max_length=30, verbose_name='auth.User'),
        ),
    ]
